FROM pychrome:latest

WORKDIR /app
ENV DISPLAY :99

ADD run.sh /run.sh
RUN chmod a+x /run.sh

CMD /run.sh
#COPY requirements.txt .
#
#RUN pip install -r requirements.txt

#CMD ["sh", "Xvfb :99 -screen 0 1024x768x24 -ac +extension GLX +render -noreset & sleep 5"]