FROM pychrome:latest

ENV DISPLAY=:99

WORKDIR /app

#COPY requirements.txt .
#
#RUN pip install -r requirements.txt

#CMD ["sh", "Xvfb :99 -screen 0 1024x768x24 -ac +extension GLX +render -noreset & sleep 5"]